a=float(input('Enter value for a'))
b=float(input('Enter value for b'))
c=float(input('Enter value for c'))
d=(b*b)-(4*a*c)
root1=(-b-(d**0.5))/(2*a)
root2=(-b+(d**0.5))/(2*a)
print('Root1 {0} Root2 {1}'.format(root1,root2))
